version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
    restart: unless-stopped
  web:
    build: .
    command: ["bash", "-l", "-c", "python manage.py runserver 0:8000"]
    volumes:
      - .:/app/webapi
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - DJANGO_HOST=${DJANGO_HOST}
      - DJANGO_SECRET=${DJANGO_SECRET:?}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    depends_on:
      - db
    restart: unless-stopped